apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.cfg: |
    upstream backend {
        server app-1:8080;
        server app-2:8080;
    }

    server {
        listen 8080;
        location / {
            proxy_pass http://backend;
        }
    }
